--- #YAML:1.0
name: Digest-SHA3
version: 0.11
abstract: Perl extension for SHA-3
license: perl
author:
  - Mark Shelor, mshelor@cpan.org
requires:
  perl: 5.003
provides:
  Digest::SHA3:
    file: lib/Digest/SHA3.pm
    version: 0.11
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Mark Shelor
